#COMPILE EXE
#DIM ALL

FUNCTION PBMAIN () AS LONG
  CON.CAPTION$= "Remote running"
  CON.COLOR 11,0
  CON.LOC = 10, 20
  CON.SCREEN = 30,60
  CON.STDOUT "Running Remotely"
  SLEEP 2000
  CON.STDOUT "Completed"
  SLEEP 1000
  CON.CLS
END FUNCTION
